url: https://brendo1001.github.io
baseurl: /smartdigiag/

# Site settings
title: Smart Digital Agriculture
email: malone.brendan1001@gmail.com
description: "Technical expertise in environmental, agricultural and soil informatics. Embracer of data science and big data. Work emcompasses foundational research, training, information delivery and technical advice. "


# Team names, titles and social links
people:
- name: Brendan Malone
  pic: 1
  position: Technical consultant 
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/soilmalone
  - title: linkedin
    url: https://www.linkedin.com/in/brendan-malone-7aa8a462
  - title: bitbucket 
    url: http://bitbucket.org/brendo1001
  - title: github
    url: http://github.com/brendo1001

# Postal address (add as many lines as necessary)
address:
  - line: 1 Central Ave
  - line: Eveleigh, NSW 2015, Australia

# Build settings
markdown: kramdown
permalink: pretty
