url: https://brendo1001.github.io
baseurl: /smartdigiag/

gems: ['jekyll/scholar']

# Site settings
title: Smart Digital Agriculture
email: malone.brendan1001@gmail.com
description: "Technical expertise in environmental, agricultural and soil informatics. Embracer of data science and big data. Work emcompasses foundational research, training, information delivery and technical advice. "


# Team names, titles and social links
people:
- name: Brendan Malone
  pic: 1
  position: Technical consultant 
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/soilmalone
  - title: linkedin
    url: https://www.linkedin.com/in/brendan-malone-7aa8a462
  - title: bitbucket 
    url: http://bitbucket.org/brendo1001
  - title: github
    url: http://github.com/brendo1001

# Postal address (add as many lines as necessary)
address:
  - line: 1 Central Ave
  - line: Eveleigh, NSW 2015, Australia


# Publication citations
scholar:
  scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Build settings
markdown: kramdown
permalink: pretty
